### ISSUE TITLE
Future request Competitie Mode

### ISSUE THREAD

**Issue by WilliamFinch** [crAZiAc/fokkersfishingblazor#10]
**Fokkers Visdag regels**.

Er wordt gevist in Teams van twee deelnemers. De teams mogen zelf hun Team naam opgeven. 

Het doel van de wedstrijd is het vangen van 3 Snoeken, 3 Snoekbaarzen en 3 Baarzen. Alleen de grootste drie per soort tellen mee. upgrades zorgen er voor dat de laagste vangst van de lijst valt (Niet verwijderen). Het vangen van  3 vissen van 1 soort levert een bonus op en een volle kaart levert ook bonus punten op. 

**Vangstregistratie en goedkeuring**
De vis wordt met de neus tegen het meetbord gefotografeerd en geregisteerd in de visapp. De deelnemer gaat ook met de vis in de hand op de foto. De jury beoordeeld de maat aan de hand van de foto. waarna de vis pas wordt geregisteerd op het leaderboard

**Puntentelling**
Elke centimeter vis telt als 1 punt
3 Snoeken levert eenmalig 20 bonus punten op
3 Snoekbaarzen levert eenmalig 20 bonus  punten op
3 Baarzen levert eenmalig 20 bonus punten op
Alle 3 de soorten levert 100 bonus punten op
Er zijn dus in totaal 160 bonus punten te behalen. 

**Individuele prijzen**
Voor de statistieken zou het mooi zijn wanneer we de grootste snoek, snoekbaars en baars van de dag individueel kunnen belonen.

**Deelnemer weergave en Leaderboard**
Tijdens de wedstrijd ziet de deelnemer zijn beste drie vissen per soort gedurende de gehele wedstrijd, zodat bekend waar de upgarde te halen zijn. Het leaderboard zou moeten bestaan uit een weergave van de 3 snoeken , 3 snoekbaarzen en 3 baarzen per team inclusief de punten. Een foto hierbij is geen must, wellicht als optie via een link achter de registratie. 

**Prijsuitreiking en wedstrijd element**
Niet perse noodzakelijk maar wel mooi wanneer de einduitslag al niet meteen op het water bekend is doordat iedereen elkaars score kan zien is dat het leaderboard. Het leaderboard vanaf een bepaalde tijd op niet beschikbaar zetten voordeelnemers, maar wel voor de wedstrijdleiding zetten zou perfect zijn. Na de prijsuitreiking moet het volledige leaderboard weer beschikbaar gemaakt kunnen worden.

**Submit competition fish**  
Voor de stats Fokkers is het handig om Alle gevangen competitie vissen in één keer te submitten naar de reguliere vangstenlijst

Hopelijk een helder verhaal ander kom maar in de lucht

**Comment by crAZiAc** [comment]
Partial setup completed. Still need to be done: Teams and assignment of team members.

**Comment by crAZiAc** [comment]
Team assignments and teams done
