### ISSUE TITLE
Meetbandfoto wat karig tenopzicht van de grote foro

### ISSUE THREAD

**Issue by WilliamFinch** [crAZiAc/fokkersfishingblazor#11]
Wanneer het op het foto ikoontje klikt komt er in een popup de meetband foto, deze is wat klein en niet schaalbaar
<img width="865" alt="meetband foto" src="https://user-images.githubusercontent.com/9060683/150696520-22b3ed5e-c424-41b5-8e7f-d28fadbc5beb.png">

**Comment by crAZiAc** [comment]
This has been fixed. We now show measure photos in the same size as the main photo. Also, admins are able to download the measure photo for detailed viewing if needed.
