### ISSUE TITLE
Staand genomen foto's

### ISSUE THREAD

**Issue by WilliamFinch** [crAZiAc/fokkersfishingblazor#12]
Staand genomen foto's vallen voor de helft weg
<img width="903" alt="2022-01-23 21_25_27-FokkersFishing and 4 more pages - Work - Microsoft​ Edge" src="https://user-images.githubusercontent.com/9060683/150696757-88aded73-49fd-48c8-9c65-912a2c44d99d.png">

**Comment by crAZiAc** [comment]
This has been fixed!
