### ISSUE TITLE
Add new catch screen issue

### ISSUE THREAD

**Issue by MrF1nch** [crAZiAc/fokkersfishingblazor#22]
after choosing the fisherman the e-mail adress is added, this makes the screen wider.  

Before
![3f87dc39-7f73-4699-95c6-b500df36f3ff](https://user-images.githubusercontent.com/7027960/192150052-44530eb8-dc89-4f16-a111-fe9316e711b9.jpg)

After

![91e7160a-c965-4107-a2a3-f05cbd2700cd](https://user-images.githubusercontent.com/7027960/192150148-8c0124c0-e61b-4a01-8fbd-6207cd9a1073.jpg)

The left falls of the  side of the screen

**Comment by crAZiAc** [comment]
Fixed.
